version: '3.2'
services:
    haproxy:
        container_name: haproxy
        restart: unless-stopped
        image: haproxy
        ports:
            - "80:8080"
        volumes:
            - ./haproxy:/usr/local/etc/haproxy
            
    pwd:
        # pwd daemon container always needs to be named this way
        container_name: pwd
        restart: unless-stopped
        # use the latest golang image
        image: golang
        # go to the right place and starts the app
        command: /bin/sh -c 'ssh-keygen -N "" -t rsa -f /etc/ssh/ssh_host_rsa_key >/dev/null; cd /go/src/github.com/damorimRG/frisk-back; go run api.go -save /pwd/sessions -name l2'
        volumes:
            # since this app creates networks and launches containers, we need to talk to docker daemon
            - /var/run/docker.sock:/var/run/docker.sock
            # mount the box mounted shared folder to the container
            - $GOPATH/src:/go/src
            - sessions:/pwd
    l2:
        container_name: l2
        restart: unless-stopped
        # use the latest golang image
        image: golang
        # go to the right place and starts the app
        command: /bin/sh -c 'ssh-keygen -N "" -t rsa -f /etc/ssh/ssh_host_rsa_key >/dev/null; cd /go/src/github.com/damorimRG/frisk-back/router/l2; go run l2.go -ssh_key_path /etc/ssh/ssh_host_rsa_key -name l2 -save /pwd/networks'
        volumes:
            - $GOPATH/src:/go/src
            - /var/run/docker.sock:/var/run/docker.sock
            - networks:/pwd
        ports:
            - "8022:22"
            - "8053:53"
            - "443:443"
    rails:
        container_name: rails
        restart: unless-stopped
        build: ./DockerFiddle
        volumes:
           - ./DockerFiddle/dbf:/usr/src/app/dbf
        ports:
           - "3000:3000"
volumes:
    sessions:
    networks:
